### ISSUE TITLE
current version command ?next does not work

### ISSUE THREAD

**Issue by neyoneit** [JBustos22/DFTwitchBot#16]
even after connectin to server it doesnt autospec

Connecting to 83.243.73.220:27960...
DefragLive is online!
Command received: next
Task exception was never retrieved
future: <Task finished coro=<event_message() done, defined at bot.py:37> exception=AttributeError("'NoneType' object has no attribute 'spec_ids'")>
Traceback (most recent call last):
  File "bot.py", line 66, in event_message
    serverstate.switch_spec('next')
  File "F:\DFTwitchBot-master\src\serverstate.py", line 198, in switch_spec
    spec_ids = STATE.spec_ids if direction == 'next' else STATE.spec_ids[::-1]
AttributeError: 'NoneType' object has no attribute 'spec_ids'

**Comment by neyoneit** [comment]
my bad.. i do apologize
