### ISSUE TITLE
msges from people with badges dont go through

### ISSUE THREAD

**Issue by neyoneit** [JBustos22/DFTwitchBot#44]
```
Spectating sutileza on cave2 in server neyon mixed III | ip: 193.86.120.146:55562
Execing command varcommand say $chsinfo(117) ^7-- you are being watched by ^37 ^7viewers
Execing command say ^mmorganich ^7>  ^2no
Chat message sent
TWITCH COMMAND RECEIVED: 'f1' from user 'txrcfc'
Pressing key {F1}
Execing command say ^7Current commands are ^3?^7nospec, ^3?^7info, ^3?^7help, ^3?^7clear, ^3?^7discord and ^3?^7howmany
Execing command say ^7Don't want to be spectated? do ^3/color1 nospec^7, To allow spectating change it ^3/color1 specme
TWITCH COMMAND RECEIVED: 'n' from user 'morganich'
Execing command follow 22
Spectating joko on cave2 in server neyon mixed III | ip: 193.86.120.146:55562
AFK detected. Strike 15/40
AFK detected. Strike 20/40
AFK detected. Strike 25/40
AFK detected. Strike 30/40
AFK detected. Strike 35/40
AFK detected. Strike 40/40
AFK. Switching...
Spectating [gt]neiT. on cave2 in server neyon mixed III | ip: 193.86.120.146:55562
AFK detected. Strike 15/40
AFK detected. Strike 20/40
AFK detected. Strike 25/40
AFK detected. Strike 30/40
AFK detected. Strike 35/40
AFK detected. Strike 40/40
AFK. Switching...
Spectating SoulAge23 on cave2 in server neyon mixed III | ip: 193.86.120.146:55562
TWITCH COMMAND RECEIVED: 'n' from user 'neyoneit'
Execing command follow 9
Spectating angeldust on cave2 in server neyon mixed III | ip: 193.86.120.146:55562
TWITCH COMMAND RECEIVED: 'n' from user 'neyoneit'
Execing command follow 10
Spectating sutileza on cave2 in server neyon mixed III | ip: 193.86.120.146:55562
TWITCH COMMAND RECEIVED: 'speclist' from user 'neyoneit'
Holding {F5} for 4.5 seconds
TWITCH COMMAND RECEIVED: 'spec' from user 'neyoneit'
Execing command follow 24
Spectating Quasar on cave2 in server neyon mixed III | ip: 193.86.120.146:55562
Execing command say ^jjoko0406 ^7>  ^2you need to go faster Mr Quasar
Chat message sent
Execing command say ^ttxrcfc ^7>  ^23
Chat message sent
Execing command say ^ttxrcfc ^7>  ^2yo
Chat message sent
Execing command say ^0 ^2^7Did you know i now support ingame commands? type ^3?^7help for more info.
Chat message sent
proxy command received
Execing command !top show
AFK detected. Strike 15/40
Activity detected. AFK counter aborted.
Traceback (most recent call last):
  File "C:\Users\neyon\AppData\Local\Programs\Python\Python37\lib\site-packages\twitchio\websocket.py", line 422, in process_data
    await self.process_actions(data, _groupsdict, badges, tags)
  File "C:\Users\neyon\AppData\Local\Programs\Python\Python37\lib\site-packages\twitchio\websocket.py", line 463, in process_actions
    user = User(author=author, channel=channel or None, tags=tags, ws=self._websocket)
  File "C:\Users\neyon\AppData\Local\Programs\Python\Python37\lib\site-packages\twitchio\dataclasses.py", line 179, in __init__
    self._badges[k] = int(v)
ValueError: invalid literal for int() with base 10: 'blue-1'
Traceback (most recent call last):
  File "C:\Users\neyon\AppData\Local\Programs\Python\Python37\lib\site-packages\twitchio\websocket.py", line 422, in process_data
    await self.process_actions(data, _groupsdict, badges, tags)
  File "C:\Users\neyon\AppData\Local\Programs\Python\Python37\lib\site-packages\twitchio\websocket.py", line 463, in process_actions
    user = User(author=author, channel=channel or None, tags=tags, ws=self._websocket)
  File "C:\Users\neyon\AppData\Local\Programs\Python\Python37\lib\site-packages\twitchio\dataclasses.py", line 179, in __init__
    self._badges[k] = int(v)
ValueError: invalid literal for int() with base 10: 'blue-1'
Traceback (most recent call last):
  File "C:\Users\neyon\AppData\Local\Programs\Python\Python37\lib\site-packages\twitchio\websocket.py", line 422, in process_data
    await self.process_actions(data, _groupsdict, badges, tags)
  File "C:\Users\neyon\AppData\Local\Programs\Python\Python37\lib\site-packages\twitchio\websocket.py", line 463, in process_actions
    user = User(author=author, channel=channel or None, tags=tags, ws=self._websocket)
  File "C:\Users\neyon\AppData\Local\Programs\Python\Python37\lib\site-packages\twitchio\dataclasses.py", line 179, in __init__
    self._badges[k] = int(v)
ValueError: invalid literal for int() with base 10: 'pink-2'
Traceback (most recent call last):
  File "C:\Users\neyon\AppData\Local\Programs\Python\Python37\lib\site-packages\twitchio\websocket.py", line 422, in process_data
    await self.process_actions(data, _groupsdict, badges, tags)
  File "C:\Users\neyon\AppData\Local\Programs\Python\Python37\lib\site-packages\twitchio\websocket.py", line 463, in process_actions
    user = User(author=author, channel=channel or None, tags=tags, ws=self._websocket)
  File "C:\Users\neyon\AppData\Local\Programs\Python\Python37\lib\site-packages\twitchio\dataclasses.py", line 179, in __init__
    self._badges[k] = int(v)
ValueError: invalid literal for int() with base 10: 'blue-1'
Traceback (most recent call last):
  File "C:\Users\neyon\AppData\Local\Programs\Python\Python37\lib\site-packages\twitchio\websocket.py", line 422, in process_data
    await self.process_actions(data, _groupsdict, badges, tags)
  File "C:\Users\neyon\AppData\Local\Programs\Python\Python37\lib\site-packages\twitchio\websocket.py", line 463, in process_actions
    user = User(author=author, channel=channel or None, tags=tags, ws=self._websocket)
  File "C:\Users\neyon\AppData\Local\Programs\Python\Python37\lib\site-packages\twitchio\dataclasses.py", line 179, in __init__
    self._badges[k] = int(v)
ValueError: invalid literal for int() with base 10: 'pink-2'
Traceback (most recent call last):
  File "C:\Users\neyon\AppData\Local\Programs\Python\Python37\lib\site-packages\twitchio\websocket.py", line 422, in process_data
    await self.process_actions(data, _groupsdict, badges, tags)
  File "C:\Users\neyon\AppData\Local\Programs\Python\Python37\lib\site-packages\twitchio\websocket.py", line 463, in process_actions
    user = User(author=author, channel=channel or None, tags=tags, ws=self._websocket)
  File "C:\Users\neyon\AppData\Local\Programs\Python\Python37\lib\site-packages\twitchio\dataclasses.py", line 179, in __init__
    self._badges[k] = int(v)
ValueError: invalid literal for int() with base 10: 'blue-1'
Traceback (most recent call last):
  File "C:\Users\neyon\AppData\Local\Programs\Python\Python37\lib\site-packages\twitchio\websocket.py", line 422, in process_data
    await self.process_actions(data, _groupsdict, badges, tags)
  File "C:\Users\neyon\AppData\Local\Programs\Python\Python37\lib\site-packages\twitchio\websocket.py", line 463, in process_actions
    user = User(author=author, channel=channel or None, tags=tags, ws=self._websocket)
  File "C:\Users\neyon\AppData\Local\Programs\Python\Python37\lib\site-packages\twitchio\dataclasses.py", line 179, in __init__
    self._badges[k] = int(v)
ValueError: invalid literal for int() with base 10: 'blue-1'
AFK detected. Strike 15/40
AFK detected. Strike 20/40
AFK detected. Strike 25/40
Traceback (most recent call last):
  File "C:\Users\neyon\AppData\Local\Programs\Python\Python37\lib\site-packages\twitchio\websocket.py", line 422, in process_data
    await self.process_actions(data, _groupsdict, badges, tags)
  File "C:\Users\neyon\AppData\Local\Programs\Python\Python37\lib\site-packages\twitchio\websocket.py", line 463, in process_actions
    user = User(author=author, channel=channel or None, tags=tags, ws=self._websocket)
  File "C:\Users\neyon\AppData\Local\Programs\Python\Python37\lib\site-packages\twitchio\dataclasses.py", line 179, in __init__
    self._badges[k] = int(v)
ValueError: invalid literal for int() with base 10: 'blue-1'
AFK detected. Strike 30/40
AFK detected. Strike 35/40
Traceback (most recent call last):
  File "C:\Users\neyon\AppData\Local\Programs\Python\Python37\lib\site-packages\twitchio\websocket.py", line 422, in process_data
    await self.process_actions(data, _groupsdict, badges, tags)
  File "C:\Users\neyon\AppData\Local\Programs\Python\Python37\lib\site-packages\twitchio\websocket.py", line 463, in process_actions
    user = User(author=author, channel=channel or None, tags=tags, ws=self._websocket)
  File "C:\Users\neyon\AppData\Local\Programs\Python\Python37\lib\site-packages\twitchio\dataclasses.py", line 179, in __init__
    self._badges[k] = int(v)
ValueError: invalid literal for int() with base 10: 'blue-1'
Traceback (most recent call last):
  File "C:\Users\neyon\AppData\Local\Programs\Python\Python37\lib\site-packages\twitchio\websocket.py", line 422, in process_data
    await self.process_actions(data, _groupsdict, badges, tags)
  File "C:\Users\neyon\AppData\Local\Programs\Python\Python37\lib\site-packages\twitchio\websocket.py", line 463, in process_actions
    user = User(author=author, channel=channel or None, tags=tags, ws=self._websocket)
  File "C:\Users\neyon\AppData\Local\Programs\Python\Python37\lib\site-packages\twitchio\dataclasses.py", line 179, in __init__
    self._badges[k] = int(v)
ValueError: invalid literal for int() with base 10: 'blue-1'
AFK detected. Strike 40/40
AFK. Switching...
Execing command say ^nneyoneit ^7>  ^2check
Spectating angeldust on cave2 in server neyon mixed III | ip: 193.86.120.146:55562
Chat message sent
Traceback (most recent call last):
  File "C:\Users\neyon\AppData\Local\Programs\Python\Python37\lib\site-packages\twitchio\websocket.py", line 422, in process_data
    await self.process_actions(data, _groupsdict, badges, tags)
  File "C:\Users\neyon\AppData\Local\Programs\Python\Python37\lib\site-packages\twitchio\websocket.py", line 463, in process_actions
    user = User(author=author, channel=channel or None, tags=tags, ws=self._websocket)
  File "C:\Users\neyon\AppData\Local\Programs\Python\Python37\lib\site-packages\twitchio\dataclasses.py", line 179, in __init__
    self._badges[k] = int(v)
ValueError: invalid literal for int() with base 10: 'blue-1'
AFK detected. Strike 15/40
Traceback (most recent call last):
  File "C:\Users\neyon\AppData\Local\Programs\Python\Python37\lib\site-packages\twitchio\websocket.py", line 422, in process_data
    await self.process_actions(data, _groupsdict, badges, tags)
  File "C:\Users\neyon\AppData\Local\Programs\Python\Python37\lib\site-packages\twitchio\websocket.py", line 463, in process_actions
    user = User(author=author, channel=channel or None, tags=tags, ws=self._websocket)
  File "C:\Users\neyon\AppData\Local\Programs\Python\Python37\lib\site-packages\twitchio\dataclasses.py", line 179, in __init__
    self._badges[k] = int(v)
ValueError: invalid literal for int() with base 10: 'blue-1'
AFK detected. Strike 20/40
Execing command say ^nneyoneit ^7>  ^2go fast quasar i have 1k points on you
Chat message sent
AFK detected. Strike 25/40
AFK detected. Strike 30/40
AFK detected. Strike 35/40
Traceback (most recent call last):
  File "C:\Users\neyon\AppData\Local\Programs\Python\Python37\lib\site-packages\twitchio\websocket.py", line 422, in process_data
    await self.process_actions(data, _groupsdict, badges, tags)
  File "C:\Users\neyon\AppData\Local\Programs\Python\Python37\lib\site-packages\twitchio\websocket.py", line 463, in process_actions
    user = User(author=author, channel=channel or None, tags=tags, ws=self._websocket)
  File "C:\Users\neyon\AppData\Local\Programs\Python\Python37\lib\site-packages\twitchio\dataclasses.py", line 179, in __init__
    self._badges[k] = int(v)
ValueError: invalid literal for int() with base 10: 'blue-1'
AFK detected. Strike 40/40
```

**Comment by JBustos22** [comment]
Issue within the package twitchio in twitchio\dataclasses.py line 179 on twitchio v. 1.1.0
